project:
  type: website
  output-dir: docs

website:
  title: "docs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: assembly_manual.qmd
        text: Preparation and Assembly
      - href: software.qmd
        text: Software
      - href: operation_and_maintenance.qmd
        text: Operation and Maintenance
    right:
      - icon: "envelope-at"
        href: "mailto:ghe@mavt.ethz.ch?subject=BSF Larvae Counting Machine"
        aria-label: Email
      - icon: github
        href: https://github.com/Global-Health-Engineering/bsf-lcm
        aria-label: GitHub
      - icon: chat-left-dots
        href: https://matrix.to/#/#ghe-open:staffchat.ethz.ch
        aria-label: Matrix
  page-footer:
      left: |
          This project was supported by the
          [Global Health Engineering Group at ETH Zurich](https://ghe.ethz.ch)
      right:
        - icon: "envelope-at"
          href: "mailto:ghe@mavt.ethz.ch?subject=BSF Larvae Counting Machine"
          aria-label: Email
        - icon: github
          href: https://github.com/Global-Health-Engineering/bsf-lcm
          aria-label: GitHub
        - icon: chat-left-dots
          href: https://matrix.to/#/#ghe-open:staffchat.ethz.ch
          aria-label: Matrix

format:
  html:
    theme:
      light: [litera, theme.scss]
    highlight-style: a11y-dark
    toc: true
    mainfont: "Atkinson Hyperlegible"
    include-in-header:
        - text: |
            <!-- Privacy-friendly analytics by Plausible -->
            <script async src="https://plausible.io/js/pa-0EptGGdYAIT1X5cmhkV1h.js"></script>
            <script>
              window.plausible=window.plausible||function(){(plausible.q=plausible.q||[]).push(arguments)},plausible.init=plausible.init||function(i){plausible.o=i||{}};
              plausible.init()
            </script>
